feat: add wait for http
SocialGouv/kosko-charts pull request #281
Opened 2020-11-06 14:44 UTC by revolunet

This allows to add an initContainer that wait for a given url to be up

2020-11-11 15:29 UTC, douglasduteil commented
@revolunet je pense qu'il serait bon d'externalizer le script comme [wait-for-postgres](https://github.com/SocialGouv/docker/tree/master/wait-for-postgres)

2020-11-12 08:26 UTC, revolunet commented
quel serait l'intérêt ?

2020-11-12 13:34 UTC, douglasduteil commented
Le mème que pour `wait-for-postgres` : testabilité, utilisabilité

2020-12-04 08:23 UTC, revolunet commented
lgtm

2020-12-04 16:48 UTC, douglasduteil requested changes

2020-12-04 16:48 UTC, douglasduteil commented on src/utils/waitForHttp.ts
>    const retries = 120; // 5s * (120) = 10min
```suggestion
```

2020-12-04 16:48 UTC, douglasduteil approved these changes

2020-12-04 16:49 UTC, merged